// Al Yedey Nigunim (על ידי ניגונים) - Chilik Frank
// Key: A minor (no accidentals), Time: 4/4
// UPDATED: Now includes rests from MusicXML
import { SongData } from "./types";

export const alYedeyNigunimUpdated: SongData = {
  id: "default-al-yedey-nigunim-updated",
  name: "Al Yedey Nigunim (Updated)",
  hebrewName: "על ידי ניגונים",
  description: "צ'יליק פרנק",
  notes: [
    // ═══════════════════════════════════════════════════════════════════
    // VERSE 1 (Measures 1-8)
    // ═══════════════════════════════════════════════════════════════════
    { id: "ayn-1", pitch: "A4", duration: 0.5, absoluteBeat: 0 },
    { id: "ayn-2", pitch: "E5", duration: 0.5, absoluteBeat: 0.5 },
    { id: "ayn-3", pitch: "D5", duration: 0.5, absoluteBeat: 1.0 },
    { id: "ayn-4", pitch: "C5", duration: 0.5, absoluteBeat: 1.5 },
    { id: "ayn-5", pitch: "D5", duration: 0.5, absoluteBeat: 2.0 },
    { id: "ayn-6", pitch: "C5", duration: 1.5, absoluteBeat: 2.5 },
    { id: "ayn-7", pitch: "D5", duration: 1.0, absoluteBeat: 4.0 },
    { id: "ayn-8", pitch: "C5", duration: 0.5, absoluteBeat: 5.0 },
    { id: "ayn-9", pitch: "B4", duration: 0.5, absoluteBeat: 5.5 },
    { id: "ayn-10", pitch: "A4", duration: 2.0, absoluteBeat: 6.0 },
    { id: "ayn-11", pitch: "A4", duration: 0.5, absoluteBeat: 8.0 },
    { id: "ayn-12", pitch: "E5", duration: 0.5, absoluteBeat: 8.5 },
    { id: "ayn-13", pitch: "D5", duration: 0.5, absoluteBeat: 9.0 },
    { id: "ayn-14", pitch: "C5", duration: 0.5, absoluteBeat: 9.5 },
    { id: "ayn-15", pitch: "D5", duration: 0.5, absoluteBeat: 10.0 },
    { id: "ayn-16", pitch: "C5", duration: 1.5, absoluteBeat: 10.5 },
    { id: "ayn-17", pitch: "D5", duration: 1.0, absoluteBeat: 12.0 },
    { id: "ayn-18", pitch: "G5", duration: 0.5, absoluteBeat: 13.0 },
    { id: "ayn-19", pitch: "F5", duration: 0.5, absoluteBeat: 13.5 },
    { id: "ayn-20", pitch: "E5", duration: 2.0, absoluteBeat: 14.0 },
    { id: "ayn-21", pitch: "A4", duration: 0.5, absoluteBeat: 16.0 },
    { id: "ayn-22", pitch: "E5", duration: 0.5, absoluteBeat: 16.5 },
    { id: "ayn-23", pitch: "D5", duration: 0.5, absoluteBeat: 17.0 },
    { id: "ayn-24", pitch: "C5", duration: 0.5, absoluteBeat: 17.5 },
    { id: "ayn-25", pitch: "D5", duration: 0.5, absoluteBeat: 18.0 },
    { id: "ayn-26", pitch: "C5", duration: 1.5, absoluteBeat: 18.5 },
    { id: "ayn-27", pitch: "D5", duration: 1.0, absoluteBeat: 20.0 },
    { id: "ayn-28", pitch: "C5", duration: 0.5, absoluteBeat: 21.0 },
    { id: "ayn-29", pitch: "B4", duration: 0.5, absoluteBeat: 21.5 },
    { id: "ayn-30", pitch: "A4", duration: 1.0, absoluteBeat: 22.0 },
    { id: "ayn-31", pitch: "A4", duration: 0.5, absoluteBeat: 23.0 },
    { id: "ayn-32", pitch: "B4", duration: 0.5, absoluteBeat: 23.5 },
    { id: "ayn-33", pitch: "C5", duration: 1.0, absoluteBeat: 24.0 },
    { id: "ayn-34", pitch: "B4", duration: 0.5, absoluteBeat: 25.0 },
    { id: "ayn-35", pitch: "A4", duration: 0.5, absoluteBeat: 25.5 },
    { id: "ayn-36", pitch: "B4", duration: 1.0, absoluteBeat: 26.0 },
    { id: "ayn-37", pitch: "A4", duration: 0.5, absoluteBeat: 27.0 },
    { id: "ayn-38", pitch: "G4", duration: 0.5, absoluteBeat: 27.5 },
    { id: "ayn-39", pitch: "A4", duration: 4.0, absoluteBeat: 28.0 },

    // ═══════════════════════════════════════════════════════════════════
    // CHORUS (Measures 9-18)
    // ═══════════════════════════════════════════════════════════════════
    { id: "ayn-40", pitch: "A4", duration: 2.0, absoluteBeat: 32.0 },
    { id: "ayn-r1", pitch: "REST", duration: 0.5, absoluteBeat: 34.0 },
    { id: "ayn-41", pitch: "G4", duration: 0.5, absoluteBeat: 34.5 },
    { id: "ayn-42", pitch: "A4", duration: 0.5, absoluteBeat: 35.0 },
    { id: "ayn-43", pitch: "B4", duration: 0.5, absoluteBeat: 35.5 },
    { id: "ayn-44", pitch: "C5", duration: 1.0, absoluteBeat: 36.0 },
    { id: "ayn-45", pitch: "C5", duration: 1.0, absoluteBeat: 37.0 },
    { id: "ayn-46", pitch: "C5", duration: 1.0, absoluteBeat: 38.0 },
    { id: "ayn-47", pitch: "C5", duration: 1.0, absoluteBeat: 39.0 },
    { id: "ayn-r2", pitch: "REST", duration: 0.5, absoluteBeat: 40.0 },
    { id: "ayn-48", pitch: "A4", duration: 0.5, absoluteBeat: 40.5 },
    { id: "ayn-49", pitch: "C5", duration: 0.5, absoluteBeat: 41.0 },
    { id: "ayn-50", pitch: "A4", duration: 0.5, absoluteBeat: 41.5 },
    { id: "ayn-51", pitch: "G4", duration: 0.5, absoluteBeat: 42.0 },
    { id: "ayn-52", pitch: "G4", duration: 0.5, absoluteBeat: 42.5 },
    { id: "ayn-53", pitch: "A4", duration: 0.5, absoluteBeat: 43.0 },
    { id: "ayn-54", pitch: "B4", duration: 0.5, absoluteBeat: 43.5 },
    { id: "ayn-55", pitch: "C5", duration: 1.0, absoluteBeat: 44.0 },
    { id: "ayn-56", pitch: "C5", duration: 1.0, absoluteBeat: 45.0 },
    { id: "ayn-57", pitch: "C5", duration: 1.0, absoluteBeat: 46.0 },
    { id: "ayn-58", pitch: "C5", duration: 1.0, absoluteBeat: 47.0 },
    { id: "ayn-r3", pitch: "REST", duration: 0.5, absoluteBeat: 48.0 },
    { id: "ayn-59", pitch: "A4", duration: 0.5, absoluteBeat: 48.5 },
    { id: "ayn-60", pitch: "C5", duration: 0.5, absoluteBeat: 49.0 },
    { id: "ayn-61", pitch: "A4", duration: 0.5, absoluteBeat: 49.5 },
    { id: "ayn-62", pitch: "G4", duration: 0.5, absoluteBeat: 50.0 },
    { id: "ayn-63", pitch: "G4", duration: 0.5, absoluteBeat: 50.5 },
    { id: "ayn-64", pitch: "A4", duration: 0.5, absoluteBeat: 51.0 },
    { id: "ayn-65", pitch: "B4", duration: 0.5, absoluteBeat: 51.5 },
    { id: "ayn-66", pitch: "C5", duration: 1.0, absoluteBeat: 52.0 },
    { id: "ayn-67", pitch: "C5", duration: 1.0, absoluteBeat: 53.0 },
    { id: "ayn-68", pitch: "C5", duration: 1.0, absoluteBeat: 54.0 },
    { id: "ayn-69", pitch: "C5", duration: 1.0, absoluteBeat: 55.0 },
    { id: "ayn-r4", pitch: "REST", duration: 0.5, absoluteBeat: 56.0 },
    { id: "ayn-70", pitch: "C5", duration: 0.5, absoluteBeat: 56.5 },
    { id: "ayn-71", pitch: "B4", duration: 0.5, absoluteBeat: 57.0 },
    { id: "ayn-72", pitch: "A4", duration: 0.5, absoluteBeat: 57.5 },
    { id: "ayn-73", pitch: "D5", duration: 1.0, absoluteBeat: 58.0 },
    { id: "ayn-74", pitch: "A4", duration: 0.5, absoluteBeat: 59.0 },
    { id: "ayn-75", pitch: "B4", duration: 0.5, absoluteBeat: 59.5 },
    { id: "ayn-76", pitch: "C5", duration: 1.0, absoluteBeat: 60.0 },
    { id: "ayn-77", pitch: "B4", duration: 0.5, absoluteBeat: 61.0 },
    { id: "ayn-78", pitch: "A4", duration: 0.5, absoluteBeat: 61.5 },
    { id: "ayn-79", pitch: "B4", duration: 1.0, absoluteBeat: 62.0 },
    { id: "ayn-80", pitch: "A4", duration: 0.5, absoluteBeat: 63.0 },
    { id: "ayn-81", pitch: "G4", duration: 0.5, absoluteBeat: 63.5 },
    { id: "ayn-82", pitch: "A4", duration: 2.0, absoluteBeat: 64.0 },
    { id: "ayn-r5", pitch: "REST", duration: 0.5, absoluteBeat: 66.0 },
    { id: "ayn-83", pitch: "G4", duration: 0.5, absoluteBeat: 66.5 },
    { id: "ayn-84", pitch: "A4", duration: 0.5, absoluteBeat: 67.0 },
    { id: "ayn-85", pitch: "B4", duration: 0.5, absoluteBeat: 67.5 },
    { id: "ayn-86", pitch: "A4", duration: 4.0, absoluteBeat: 68.0 },
  ],

  repeatMarkers: [],

  lyrics: [],

  settings: {
    tempo: 88,
    timeSignature: { numerator: 4, denominator: 4 },
    staffLines: 5,
  },

  releaseDate: "2026-02-03",

  transcriptionNotes: {
    original: {
      key: "A minor (no accidentals)",
      timeSignature: "4/4",
      features: [
        "Clean natural minor melody",
        "No accidentals - beginner friendly",
        "Repetitive chorus pattern",
        "5 rests added from MusicXML source",
      ],
    },
    changes: [
      {
        what: "Added 5 rests from MusicXML extraction",
        why: "Original sheet music has rests that were missing from first transcription",
      },
    ],
    sources: {
      sheetMusic: "Israeli Note - Al Yedey Nigunim (Chilik Frank)",
    },
    transcribedDate: "2026-02-04",
  },
};
