// Didan Notzach (דידן נצח) - "We Were Victorious"
// A Song for 5 Teves - Chabad Niggun
// Key: F major, Time: 4/4, Tempo: 120
import { SongData } from "./types";

export const didanNotzach: SongData = {
  id: "default-didan",
  name: "Didan Notzach (דידן נצח)",
  notes: [
    // === SECTION A (Measures 1-4, beats 0-15) ===
    // Key: F major (1 flat = Bb). Melody outlines F-A-C with Bb passing tones
    // M1: F A C A | Bb G A A (all eighths)
    { id: "didan-0", pitch: "F4", duration: 0.5, absoluteBeat: 0 },
    { id: "didan-1", pitch: "A4", duration: 0.5, absoluteBeat: 0.5 },
    { id: "didan-2", pitch: "C5", duration: 0.5, absoluteBeat: 1 },
    { id: "didan-3", pitch: "A4", duration: 0.5, absoluteBeat: 1.5 },
    { id: "didan-4", pitch: "Bb4", duration: 0.5, absoluteBeat: 2 },
    { id: "didan-5", pitch: "G4", duration: 0.5, absoluteBeat: 2.5 },
    { id: "didan-6", pitch: "A4", duration: 0.5, absoluteBeat: 3 },
    { id: "didan-7", pitch: "A4", duration: 0.5, absoluteBeat: 3.5 },
    // M2: F F C A | Bb G A A
    { id: "didan-8", pitch: "F4", duration: 0.5, absoluteBeat: 4 },
    { id: "didan-9", pitch: "F4", duration: 0.5, absoluteBeat: 4.5 },
    { id: "didan-10", pitch: "C5", duration: 0.5, absoluteBeat: 5 },
    { id: "didan-11", pitch: "A4", duration: 0.5, absoluteBeat: 5.5 },
    { id: "didan-12", pitch: "Bb4", duration: 0.5, absoluteBeat: 6 },
    { id: "didan-13", pitch: "G4", duration: 0.5, absoluteBeat: 6.5 },
    { id: "didan-14", pitch: "A4", duration: 0.5, absoluteBeat: 7 },
    { id: "didan-15", pitch: "A4", duration: 0.5, absoluteBeat: 7.5 },
    // M3: F A C A | Bb G A A (same as M1)
    { id: "didan-16", pitch: "F4", duration: 0.5, absoluteBeat: 8 },
    { id: "didan-17", pitch: "A4", duration: 0.5, absoluteBeat: 8.5 },
    { id: "didan-18", pitch: "C5", duration: 0.5, absoluteBeat: 9 },
    { id: "didan-19", pitch: "A4", duration: 0.5, absoluteBeat: 9.5 },
    { id: "didan-20", pitch: "Bb4", duration: 0.5, absoluteBeat: 10 },
    { id: "didan-21", pitch: "G4", duration: 0.5, absoluteBeat: 10.5 },
    { id: "didan-22", pitch: "A4", duration: 0.5, absoluteBeat: 11 },
    { id: "didan-23", pitch: "A4", duration: 0.5, absoluteBeat: 11.5 },
    // M4: F F C A | Bb G A F (variation ending on F)
    { id: "didan-24", pitch: "F4", duration: 0.5, absoluteBeat: 12 },
    { id: "didan-25", pitch: "F4", duration: 0.5, absoluteBeat: 12.5 },
    { id: "didan-26", pitch: "C5", duration: 0.5, absoluteBeat: 13 },
    { id: "didan-27", pitch: "A4", duration: 0.5, absoluteBeat: 13.5 },
    { id: "didan-28", pitch: "Bb4", duration: 0.5, absoluteBeat: 14 },
    { id: "didan-29", pitch: "G4", duration: 0.5, absoluteBeat: 14.5 },
    { id: "didan-30", pitch: "A4", duration: 0.5, absoluteBeat: 15 },
    { id: "didan-31", pitch: "F4", duration: 0.5, absoluteBeat: 15.5 },
    // === SECTION B (Measures 5-8, beats 16-31) ===
    // M5: G G G G (quarters under Gm chord)
    { id: "didan-32", pitch: "G4", duration: 1, absoluteBeat: 16 },
    { id: "didan-33", pitch: "G4", duration: 1, absoluteBeat: 17 },
    { id: "didan-34", pitch: "G4", duration: 1, absoluteBeat: 18 },
    { id: "didan-35", pitch: "G4", duration: 1, absoluteBeat: 19 },
    // M6: (rest) E F E. F
    { id: "didan-36", pitch: "E4", duration: 0.5, absoluteBeat: 20.5 },
    { id: "didan-37", pitch: "F4", duration: 0.5, absoluteBeat: 21 },
    { id: "didan-38", pitch: "E4", duration: 1.5, absoluteBeat: 21.5 },
    { id: "didan-39", pitch: "F4", duration: 0.5, absoluteBeat: 23 },
    // M7: G G G G
    { id: "didan-40", pitch: "G4", duration: 1, absoluteBeat: 24 },
    { id: "didan-41", pitch: "G4", duration: 1, absoluteBeat: 25 },
    { id: "didan-42", pitch: "G4", duration: 1, absoluteBeat: 26 },
    { id: "didan-43", pitch: "G4", duration: 1, absoluteBeat: 27 },
    // M8: (rest) E F E. F
    { id: "didan-44", pitch: "E4", duration: 0.5, absoluteBeat: 28.5 },
    { id: "didan-45", pitch: "F4", duration: 0.5, absoluteBeat: 29 },
    { id: "didan-46", pitch: "E4", duration: 1.5, absoluteBeat: 29.5 },
    { id: "didan-47", pitch: "F4", duration: 0.5, absoluteBeat: 31 },
  ],
  repeatMarkers: [
    {
      id: "didan-repeat-start",
      pairId: "didan-repeat",
      type: "start",
      measureNumber: 0,
    },
    {
      id: "didan-repeat-end",
      pairId: "didan-repeat",
      type: "end",
      measureNumber: 8,
    },
  ],
  lyrics: [
    // Section A - eighth note syllables
    { text: "Di", absoluteBeat: 0 },
    { text: "dan", absoluteBeat: 0.5 },
    { text: "no", absoluteBeat: 1 },
    { text: "tzach", absoluteBeat: 1.5 },
    { text: "di", absoluteBeat: 2 },
    { text: "dan", absoluteBeat: 2.5 },
    { text: "no", absoluteBeat: 3 },
    { text: "tzach", absoluteBeat: 3.5 },
    { text: "di", absoluteBeat: 4 },
    { text: "dan", absoluteBeat: 4.5 },
    { text: "no", absoluteBeat: 5 },
    { text: "tzach", absoluteBeat: 5.5 },
    { text: "di", absoluteBeat: 6 },
    { text: "dan", absoluteBeat: 6.5 },
    { text: "no", absoluteBeat: 7 },
    { text: "tzach", absoluteBeat: 7.5 },
    { text: "Di", absoluteBeat: 8 },
    { text: "dan", absoluteBeat: 8.5 },
    { text: "no", absoluteBeat: 9 },
    { text: "tzach", absoluteBeat: 9.5 },
    { text: "di", absoluteBeat: 10 },
    { text: "dan", absoluteBeat: 10.5 },
    { text: "no", absoluteBeat: 11 },
    { text: "tzach", absoluteBeat: 11.5 },
    { text: "di", absoluteBeat: 12 },
    { text: "dan", absoluteBeat: 12.5 },
    { text: "no", absoluteBeat: 13 },
    { text: "tzach", absoluteBeat: 13.5 },
    { text: "di", absoluteBeat: 14 },
    { text: "dan", absoluteBeat: 14.5 },
    { text: "no", absoluteBeat: 15 },
    { text: "tzach", absoluteBeat: 15.5 },
    // Section B - quarter notes
    { text: "Di", absoluteBeat: 16 },
    { text: "dan", absoluteBeat: 17 },
    { text: "no", absoluteBeat: 18 },
    { text: "tzach", absoluteBeat: 19 },
    { text: "di", absoluteBeat: 20.5 },
    { text: "dan", absoluteBeat: 21 },
    { text: "no", absoluteBeat: 21.5 },
    { text: "tzach", absoluteBeat: 23 },
    { text: "Di", absoluteBeat: 24 },
    { text: "dan", absoluteBeat: 25 },
    { text: "no", absoluteBeat: 26 },
    { text: "tzach", absoluteBeat: 27 },
    { text: "di", absoluteBeat: 28.5 },
    { text: "dan", absoluteBeat: 29 },
    { text: "no", absoluteBeat: 29.5 },
    { text: "tzach", absoluteBeat: 31 },
  ],
  settings: {
    tempo: 120,
    timeSignature: { numerator: 4, denominator: 4 },
  },
};
