// Dror Yikra (דרור יקרא)
// Key: C Major / A minor, Time: 2/2
// Traditional Shabbat song by Dunash ben Labrat (10th century)
import { SongData } from "./types";

export const drorYikra: SongData = {
  id: "default-dror-yikra",
  name: "Dror Yikra",
  hebrewName: "דרור יקרא",
  description: "פיוט לשבת - דונש בן לברט",
  notes: [
    // ═══════════════════════════════════════════════════════════════════
    // VERSE 1 (Measures 1-8)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-r1", pitch: "REST", duration: 1.5, absoluteBeat: 0 },
    { id: "dror-1", pitch: "G3", duration: 0.5, absoluteBeat: 1.5 },
    { id: "dror-2", pitch: "C4", duration: 1, absoluteBeat: 2 },
    { id: "dror-3", pitch: "C4", duration: 1, absoluteBeat: 3 },
    { id: "dror-4", pitch: "C4", duration: 1.5, absoluteBeat: 4 },
    { id: "dror-5", pitch: "D4", duration: 0.5, absoluteBeat: 5.5 },
    { id: "dror-6", pitch: "E4", duration: 1, absoluteBeat: 6 },
    { id: "dror-7", pitch: "E4", duration: 1, absoluteBeat: 7 },
    { id: "dror-8", pitch: "E4", duration: 1.5, absoluteBeat: 8 },
    { id: "dror-9", pitch: "C4", duration: 0.5, absoluteBeat: 9.5 },
    { id: "dror-10", pitch: "G4", duration: 1, absoluteBeat: 10 },
    { id: "dror-11", pitch: "G4", duration: 1, absoluteBeat: 11 },
    { id: "dror-12", pitch: "G4", duration: 1.5, absoluteBeat: 12 },
    { id: "dror-13", pitch: "G4", duration: 0.5, absoluteBeat: 13.5 },
    { id: "dror-14", pitch: "C5", duration: 1, absoluteBeat: 14 },
    { id: "dror-15", pitch: "B4", duration: 1, absoluteBeat: 15 },
    { id: "dror-16", pitch: "G4", duration: 1.5, absoluteBeat: 16 },
    { id: "dror-17", pitch: "G4", duration: 0.5, absoluteBeat: 17.5 },
    { id: "dror-18", pitch: "F4", duration: 0.5, absoluteBeat: 18 },
    { id: "dror-19", pitch: "E4", duration: 0.5, absoluteBeat: 18.5 },
    { id: "dror-20", pitch: "D4", duration: 0.5, absoluteBeat: 19 },
    { id: "dror-21", pitch: "C4", duration: 0.5, absoluteBeat: 19.5 },
    { id: "dror-22", pitch: "E4", duration: 1.5, absoluteBeat: 20 },
    { id: "dror-23", pitch: "D4", duration: 0.5, absoluteBeat: 21.5 },
    { id: "dror-24", pitch: "C4", duration: 1.5, absoluteBeat: 22 },
    { id: "dror-25", pitch: "A3", duration: 0.5, absoluteBeat: 23.5 },
    { id: "dror-26", pitch: "G3", duration: 1.5, absoluteBeat: 24 },
    { id: "dror-27", pitch: "G3", duration: 0.5, absoluteBeat: 25.5 },
    { id: "dror-28", pitch: "A3", duration: 0.5, absoluteBeat: 26 },
    { id: "dror-29", pitch: "C4", duration: 0.5, absoluteBeat: 26.5 },
    { id: "dror-30", pitch: "D4", duration: 0.5, absoluteBeat: 27 },
    { id: "dror-31", pitch: "E4", duration: 0.5, absoluteBeat: 27.5 },
    { id: "dror-32", pitch: "D4", duration: 1.5, absoluteBeat: 28 },
    { id: "dror-33", pitch: "C4", duration: 0.5, absoluteBeat: 29.5 },
    { id: "dror-34", pitch: "G3", duration: 2, absoluteBeat: 30 },
    { id: "dror-r2", pitch: "REST", duration: 1.5, absoluteBeat: 32 },

    // ═══════════════════════════════════════════════════════════════════
    // VERSE 2 (Measures 9-16)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-35", pitch: "G3", duration: 0.5, absoluteBeat: 33.5 },
    { id: "dror-36", pitch: "C4", duration: 1, absoluteBeat: 34 },
    { id: "dror-37", pitch: "C4", duration: 1, absoluteBeat: 35 },
    { id: "dror-38", pitch: "C4", duration: 1.5, absoluteBeat: 36 },
    { id: "dror-39", pitch: "D4", duration: 0.5, absoluteBeat: 37.5 },
    { id: "dror-40", pitch: "E4", duration: 1, absoluteBeat: 38 },
    { id: "dror-41", pitch: "E4", duration: 1, absoluteBeat: 39 },
    { id: "dror-42", pitch: "E4", duration: 1.5, absoluteBeat: 40 },
    { id: "dror-43", pitch: "C4", duration: 0.5, absoluteBeat: 41.5 },
    { id: "dror-44", pitch: "G4", duration: 1, absoluteBeat: 42 },
    { id: "dror-45", pitch: "G4", duration: 1, absoluteBeat: 43 },
    { id: "dror-46", pitch: "G4", duration: 1.5, absoluteBeat: 44 },
    { id: "dror-47", pitch: "G4", duration: 0.5, absoluteBeat: 45.5 },
    { id: "dror-48", pitch: "C5", duration: 1, absoluteBeat: 46 },
    { id: "dror-49", pitch: "B4", duration: 1, absoluteBeat: 47 },
    { id: "dror-50", pitch: "G4", duration: 2, absoluteBeat: 48 },
    { id: "dror-51", pitch: "C4", duration: 0.5, absoluteBeat: 50.5 },
    { id: "dror-52", pitch: "C4", duration: 0.5, absoluteBeat: 51 },
    { id: "dror-53", pitch: "D4", duration: 0.5, absoluteBeat: 51.5 },
    { id: "dror-54", pitch: "E4", duration: 2, absoluteBeat: 52 },
    { id: "dror-55", pitch: "G4", duration: 0.5, absoluteBeat: 54 },
    { id: "dror-56", pitch: "F4", duration: 0.5, absoluteBeat: 54.5 },
    { id: "dror-57", pitch: "E4", duration: 1, absoluteBeat: 55 },
    { id: "dror-58", pitch: "D4", duration: 1.5, absoluteBeat: 56 },
    { id: "dror-59", pitch: "G3", duration: 0.5, absoluteBeat: 57.5 },
    { id: "dror-60", pitch: "D4", duration: 0.5, absoluteBeat: 58 },
    { id: "dror-61", pitch: "D4", duration: 0.5, absoluteBeat: 58.5 },
    { id: "dror-62", pitch: "D4", duration: 0.5, absoluteBeat: 59 },
    { id: "dror-63", pitch: "E4", duration: 0.5, absoluteBeat: 59.5 },
    { id: "dror-64", pitch: "D4", duration: 1.5, absoluteBeat: 60 },
    { id: "dror-65", pitch: "C4", duration: 0.5, absoluteBeat: 61.5 },
    { id: "dror-66", pitch: "C4", duration: 2, absoluteBeat: 62 },
    { id: "dror-r3", pitch: "REST", duration: 1.5, absoluteBeat: 64 },

    // ═══════════════════════════════════════════════════════════════════
    // CHORUS (Measures 17-24)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-67", pitch: "C4", duration: 0.5, absoluteBeat: 65.5 },
    { id: "dror-68", pitch: "C5", duration: 1, absoluteBeat: 66 },
    { id: "dror-69", pitch: "C5", duration: 1, absoluteBeat: 67 },
    { id: "dror-70", pitch: "C5", duration: 1.5, absoluteBeat: 68 },
    { id: "dror-71", pitch: "C5", duration: 0.5, absoluteBeat: 69.5 },
    { id: "dror-72", pitch: "C5", duration: 1, absoluteBeat: 70 },
    { id: "dror-73", pitch: "D5", duration: 1, absoluteBeat: 71 },
    { id: "dror-74", pitch: "D5", duration: 1.5, absoluteBeat: 72 },
    { id: "dror-75", pitch: "G4", duration: 0.5, absoluteBeat: 73.5 },
    { id: "dror-76", pitch: "D5", duration: 1, absoluteBeat: 74 },
    { id: "dror-77", pitch: "E5", duration: 1, absoluteBeat: 75 },
    { id: "dror-78", pitch: "E5", duration: 1.5, absoluteBeat: 76 },
    { id: "dror-79", pitch: "D5", duration: 0.5, absoluteBeat: 77.5 },
    { id: "dror-80", pitch: "C5", duration: 1, absoluteBeat: 78 },
    { id: "dror-81", pitch: "A4", duration: 1, absoluteBeat: 79 },
    { id: "dror-82", pitch: "G4", duration: 1.5, absoluteBeat: 80 },
    { id: "dror-83", pitch: "G4", duration: 0.5, absoluteBeat: 81.5 },
    { id: "dror-84", pitch: "F4", duration: 0.5, absoluteBeat: 82 },
    { id: "dror-85", pitch: "E4", duration: 0.5, absoluteBeat: 82.5 },
    { id: "dror-86", pitch: "D4", duration: 0.5, absoluteBeat: 83 },
    { id: "dror-87", pitch: "C4", duration: 0.5, absoluteBeat: 83.5 },
    { id: "dror-88", pitch: "E4", duration: 1.5, absoluteBeat: 84 },
    { id: "dror-89", pitch: "D4", duration: 0.5, absoluteBeat: 85.5 },
    { id: "dror-90", pitch: "C4", duration: 1.5, absoluteBeat: 86 },
    { id: "dror-91", pitch: "A3", duration: 0.5, absoluteBeat: 87.5 },
    { id: "dror-92", pitch: "G3", duration: 1.5, absoluteBeat: 88 },
    { id: "dror-93", pitch: "G3", duration: 0.5, absoluteBeat: 89.5 },
    { id: "dror-94", pitch: "A3", duration: 0.5, absoluteBeat: 90 },
    { id: "dror-95", pitch: "C4", duration: 0.5, absoluteBeat: 90.5 },
    { id: "dror-96", pitch: "D4", duration: 0.5, absoluteBeat: 91 },
    { id: "dror-97", pitch: "E4", duration: 0.5, absoluteBeat: 91.5 },
    { id: "dror-98", pitch: "E4", duration: 1.5, absoluteBeat: 92 },
    { id: "dror-99", pitch: "G4", duration: 0.5, absoluteBeat: 93.5 },
    { id: "dror-100", pitch: "G4", duration: 2, absoluteBeat: 94 },
    { id: "dror-r4", pitch: "REST", duration: 1.5, absoluteBeat: 96 },

    // ═══════════════════════════════════════════════════════════════════
    // CHORUS REPEAT (Measures 25-32)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-101", pitch: "C4", duration: 0.5, absoluteBeat: 97.5 },
    { id: "dror-102", pitch: "C5", duration: 1, absoluteBeat: 98 },
    { id: "dror-103", pitch: "C5", duration: 1, absoluteBeat: 99 },
    { id: "dror-104", pitch: "C5", duration: 1.5, absoluteBeat: 100 },
    { id: "dror-105", pitch: "C5", duration: 0.5, absoluteBeat: 101.5 },
    { id: "dror-106", pitch: "C5", duration: 1, absoluteBeat: 102 },
    { id: "dror-107", pitch: "D5", duration: 1, absoluteBeat: 103 },
    { id: "dror-108", pitch: "D5", duration: 1.5, absoluteBeat: 104 },
    { id: "dror-109", pitch: "G4", duration: 0.5, absoluteBeat: 105.5 },
    { id: "dror-110", pitch: "D5", duration: 1, absoluteBeat: 106 },
    { id: "dror-111", pitch: "E5", duration: 1, absoluteBeat: 107 },
    { id: "dror-112", pitch: "E5", duration: 1.5, absoluteBeat: 108 },
    { id: "dror-113", pitch: "D5", duration: 0.5, absoluteBeat: 109.5 },
    { id: "dror-114", pitch: "C5", duration: 1, absoluteBeat: 110 },
    { id: "dror-115", pitch: "A4", duration: 1, absoluteBeat: 111 },
    { id: "dror-116", pitch: "G4", duration: 2, absoluteBeat: 112 },
    { id: "dror-117", pitch: "C4", duration: 0.5, absoluteBeat: 114.5 },
    { id: "dror-118", pitch: "C4", duration: 0.5, absoluteBeat: 115 },
    { id: "dror-119", pitch: "D4", duration: 0.5, absoluteBeat: 115.5 },
    { id: "dror-120", pitch: "E4", duration: 2, absoluteBeat: 116 },
    { id: "dror-121", pitch: "G4", duration: 0.5, absoluteBeat: 118 },
    { id: "dror-122", pitch: "F4", duration: 0.5, absoluteBeat: 118.5 },
    { id: "dror-123", pitch: "E4", duration: 1, absoluteBeat: 119 },
    { id: "dror-124", pitch: "D4", duration: 1.5, absoluteBeat: 120 },
    { id: "dror-125", pitch: "G3", duration: 0.5, absoluteBeat: 121.5 },
    { id: "dror-126", pitch: "D4", duration: 0.5, absoluteBeat: 122 },
    { id: "dror-127", pitch: "D4", duration: 0.5, absoluteBeat: 122.5 },
    { id: "dror-128", pitch: "D4", duration: 0.5, absoluteBeat: 123 },
    { id: "dror-129", pitch: "E4", duration: 0.5, absoluteBeat: 123.5 },
    { id: "dror-130", pitch: "D4", duration: 1.5, absoluteBeat: 124 },
    { id: "dror-131", pitch: "C4", duration: 0.5, absoluteBeat: 125.5 },
    { id: "dror-132", pitch: "C4", duration: 2, absoluteBeat: 126 },
    { id: "dror-r5", pitch: "REST", duration: 3, absoluteBeat: 128 },

    // ═══════════════════════════════════════════════════════════════════
    // BRIDGE (Measures 33-36)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-133", pitch: "C4", duration: 0.5, absoluteBeat: 131 },
    { id: "dror-134", pitch: "D4", duration: 0.5, absoluteBeat: 131.5 },
    { id: "dror-135", pitch: "E4", duration: 2, absoluteBeat: 132 },
    { id: "dror-136", pitch: "F4", duration: 0.5, absoluteBeat: 134 },
    { id: "dror-137", pitch: "E4", duration: 0.5, absoluteBeat: 134.5 },
    { id: "dror-138", pitch: "D4", duration: 0.5, absoluteBeat: 135 },
    { id: "dror-139", pitch: "C4", duration: 0.5, absoluteBeat: 135.5 },
    { id: "dror-140", pitch: "D4", duration: 3, absoluteBeat: 136 },
    { id: "dror-141", pitch: "E4", duration: 0.5, absoluteBeat: 139 },
    { id: "dror-142", pitch: "F4", duration: 0.5, absoluteBeat: 139.5 },
    { id: "dror-143", pitch: "G4", duration: 3, absoluteBeat: 140 },
    { id: "dror-144", pitch: "A4", duration: 0.5, absoluteBeat: 143 },
    { id: "dror-145", pitch: "G4", duration: 1, absoluteBeat: 143.5 },
    { id: "dror-r6", pitch: "REST", duration: 24.5, absoluteBeat: 144.5 },

    // ═══════════════════════════════════════════════════════════════════
    // CLIMAX SECTION (Measures 43-56)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-146", pitch: "A4", duration: 3, absoluteBeat: 169 },
    { id: "dror-147", pitch: "B4", duration: 1, absoluteBeat: 172 },
    { id: "dror-148", pitch: "B4", duration: 1, absoluteBeat: 173 },
    { id: "dror-149", pitch: "A4", duration: 2, absoluteBeat: 174 },
    { id: "dror-150", pitch: "A4", duration: 0.5, absoluteBeat: 176 },
    { id: "dror-151", pitch: "B4", duration: 0.5, absoluteBeat: 176.5 },
    { id: "dror-152", pitch: "C5", duration: 3, absoluteBeat: 177 },
    { id: "dror-153", pitch: "D5", duration: 1, absoluteBeat: 180 },
    { id: "dror-154", pitch: "D5", duration: 2, absoluteBeat: 181 },
    { id: "dror-155", pitch: "D5", duration: 1, absoluteBeat: 183 },
    { id: "dror-156", pitch: "E5", duration: 1, absoluteBeat: 184 },
    { id: "dror-157", pitch: "E5", duration: 3, absoluteBeat: 185 },
    { id: "dror-158", pitch: "F5", duration: 1, absoluteBeat: 188 },
    { id: "dror-159", pitch: "E5", duration: 1, absoluteBeat: 189 },
    { id: "dror-160", pitch: "D5", duration: 1, absoluteBeat: 190 },
    { id: "dror-161", pitch: "C5", duration: 2, absoluteBeat: 191 },
    { id: "dror-162", pitch: "C5", duration: 1, absoluteBeat: 193 },
    { id: "dror-163", pitch: "D5", duration: 1, absoluteBeat: 194 },
    { id: "dror-164", pitch: "D5", duration: 3, absoluteBeat: 195 },
    { id: "dror-165", pitch: "C5", duration: 0.5, absoluteBeat: 198 },
    { id: "dror-166", pitch: "D5", duration: 0.5, absoluteBeat: 198.5 },
    { id: "dror-167", pitch: "Eb5", duration: 1.5, absoluteBeat: 199 },
    { id: "dror-168", pitch: "D5", duration: 0.5, absoluteBeat: 200.5 },
    { id: "dror-169", pitch: "C5", duration: 1, absoluteBeat: 201 },
    { id: "dror-170", pitch: "Ab4", duration: 1, absoluteBeat: 202 },
    { id: "dror-171", pitch: "G4", duration: 3, absoluteBeat: 203 },

    // ═══════════════════════════════════════════════════════════════════
    // FINALE (Measures 52-56)
    // ═══════════════════════════════════════════════════════════════════
    { id: "dror-172", pitch: "C4", duration: 0.5, absoluteBeat: 206 },
    { id: "dror-173", pitch: "D4", duration: 0.5, absoluteBeat: 206.5 },
    { id: "dror-174", pitch: "E4", duration: 2, absoluteBeat: 207 },
    { id: "dror-175", pitch: "G4", duration: 0.5, absoluteBeat: 209 },
    { id: "dror-176", pitch: "F4", duration: 0.5, absoluteBeat: 209.5 },
    { id: "dror-177", pitch: "E4", duration: 1, absoluteBeat: 210 },
    { id: "dror-178", pitch: "D4", duration: 1.5, absoluteBeat: 211 },
    { id: "dror-179", pitch: "G3", duration: 0.5, absoluteBeat: 212.5 },
    { id: "dror-180", pitch: "D4", duration: 0.5, absoluteBeat: 213 },
    { id: "dror-181", pitch: "D4", duration: 0.5, absoluteBeat: 213.5 },
    { id: "dror-182", pitch: "D4", duration: 0.5, absoluteBeat: 214 },
    { id: "dror-183", pitch: "E4", duration: 0.5, absoluteBeat: 214.5 },
    { id: "dror-184", pitch: "D4", duration: 1.5, absoluteBeat: 215 },
    { id: "dror-185", pitch: "C4", duration: 0.5, absoluteBeat: 216.5 },
    { id: "dror-186", pitch: "C4", duration: 2, absoluteBeat: 217 },
  ],

  repeatMarkers: [
    {
      id: "dror-repeat-end",
      pairId: "dror-repeat-1",
      type: "end",
      measureNumber: 32,
    },
  ],

  lyrics: [],

  settings: {
    tempo: 100,
    timeSignature: { numerator: 2, denominator: 2 },
    staffLines: 5,
  },

  releaseDate: "2026-02-03",

  transcriptionNotes: {
    original: {
      key: "C Major / A minor",
      timeSignature: "2/2 (cut time)",
      features: [
        "Traditional Shabbat piyut",
        "10th century poem by Dunash ben Labrat",
        "Rests added for phrase breaks",
        "Accidentals: Eb5, Ab4 in climax section",
        "Updated from MuseScore Studio 4.6.5 source",
      ],
    },
    changes: [],
    sources: {
      sheetMusic: "Israeli Note - Dror Yikra (MusicXML export)",
    },
    transcribedDate: "2026-02-04",
  },
};
