// Mashiach Now (משיח נאו) - Chabad Song
// Verse + Chorus + Ending
import { SongData } from "./types";

export const mashiachNow: SongData = {
  id: "default-mashiach",
  name: "Mashiach Now (משיח נאו)",
  notes: [
    // === VERSE (Measures 1-2, beats 0-7) ===
    { id: "mashiach-0", pitch: "D4", duration: 0.5, absoluteBeat: 0 },
    { id: "mashiach-1", pitch: "D4", duration: 0.5, absoluteBeat: 0.5 },
    { id: "mashiach-2", pitch: "D4", duration: 0.5, absoluteBeat: 1 },
    { id: "mashiach-3", pitch: "E4", duration: 0.5, absoluteBeat: 1.5 },
    { id: "mashiach-4", pitch: "F4", duration: 0.5, absoluteBeat: 2 },
    { id: "mashiach-5", pitch: "F4", duration: 0.5, absoluteBeat: 2.5 },
    { id: "mashiach-6", pitch: "F4", duration: 0.5, absoluteBeat: 3 },
    { id: "mashiach-7", pitch: "G4", duration: 0.5, absoluteBeat: 3.5 },
    { id: "mashiach-8", pitch: "A4", duration: 0.5, absoluteBeat: 4 },
    { id: "mashiach-9", pitch: "A4", duration: 0.5, absoluteBeat: 4.5 },
    { id: "mashiach-10", pitch: "A4", duration: 0.5, absoluteBeat: 5 },
    { id: "mashiach-11", pitch: "G4", duration: 0.5, absoluteBeat: 5.5 },
    { id: "mashiach-12", pitch: "F4", duration: 0.5, absoluteBeat: 6 },
    { id: "mashiach-13", pitch: "E4", duration: 0.5, absoluteBeat: 6.5 },
    { id: "mashiach-14", pitch: "D4", duration: 1, absoluteBeat: 7 },
    // === CHORUS (Measures 3-5, beats 8-19) ===
    { id: "mashiach-15", pitch: "G4", duration: 1, absoluteBeat: 8 },
    { id: "mashiach-16", pitch: "G4", duration: 1, absoluteBeat: 9 },
    { id: "mashiach-17", pitch: "E4", duration: 0.5, absoluteBeat: 10 },
    { id: "mashiach-18", pitch: "G4", duration: 0.5, absoluteBeat: 10.5 },
    { id: "mashiach-19", pitch: "E4", duration: 0.5, absoluteBeat: 11 },
    { id: "mashiach-20", pitch: "G4", duration: 0.5, absoluteBeat: 11.5 },
    { id: "mashiach-21", pitch: "F4", duration: 1, absoluteBeat: 12 },
    { id: "mashiach-22", pitch: "F4", duration: 1, absoluteBeat: 13 },
    { id: "mashiach-23", pitch: "F4", duration: 0.5, absoluteBeat: 14 },
    { id: "mashiach-24", pitch: "D4", duration: 0.5, absoluteBeat: 14.5 },
    { id: "mashiach-25", pitch: "F4", duration: 0.5, absoluteBeat: 15 },
    { id: "mashiach-26", pitch: "D4", duration: 0.5, absoluteBeat: 15.5 },
    { id: "mashiach-27", pitch: "G4", duration: 1, absoluteBeat: 16 },
    { id: "mashiach-28", pitch: "G4", duration: 1, absoluteBeat: 17 },
    { id: "mashiach-29", pitch: "F4", duration: 0.5, absoluteBeat: 18 },
    { id: "mashiach-30", pitch: "D4", duration: 0.5, absoluteBeat: 18.5 },
    { id: "mashiach-31", pitch: "F4", duration: 0.5, absoluteBeat: 19 },
    { id: "mashiach-32", pitch: "D4", duration: 0.5, absoluteBeat: 19.5 },
    // === ENDING (Measures 6-7, beats 20-27) ===
    { id: "mashiach-33", pitch: "A4", duration: 1, absoluteBeat: 20 },
    { id: "mashiach-34", pitch: "G4", duration: 1, absoluteBeat: 21 },
    { id: "mashiach-35", pitch: "F4", duration: 1, absoluteBeat: 22 },
    { id: "mashiach-36", pitch: "G4", duration: 1, absoluteBeat: 23 },
    { id: "mashiach-37", pitch: "A4", duration: 4, absoluteBeat: 24 },
  ],
  repeatMarkers: [
    {
      id: "mashiach-repeat-start",
      pairId: "mashiach-repeat",
      type: "start",
      measureNumber: 2,
    },
    {
      id: "mashiach-repeat-end",
      pairId: "mashiach-repeat",
      type: "end",
      measureNumber: 6,
    },
  ],
  lyrics: [
    // Verse
    { text: "Am", absoluteBeat: 0 },
    { text: "Yis", absoluteBeat: 0.5 },
    { text: "ra", absoluteBeat: 1 },
    { text: "el", absoluteBeat: 1.5 },
    { text: "Have", absoluteBeat: 2 },
    { text: "no", absoluteBeat: 2.5 },
    { text: "fear", absoluteBeat: 3 },
    { text: "Ma-", absoluteBeat: 3.5 },
    { text: "shi", absoluteBeat: 4 },
    { text: "ach", absoluteBeat: 4.5 },
    { text: "will", absoluteBeat: 5 },
    { text: "be", absoluteBeat: 5.5 },
    { text: "here", absoluteBeat: 6 },
    { text: "this", absoluteBeat: 6.5 },
    { text: "year", absoluteBeat: 7 },
    // Chorus
    { text: "We", absoluteBeat: 8 },
    { text: "want", absoluteBeat: 9 },
    { text: "Ma", absoluteBeat: 10 },
    { text: "shi", absoluteBeat: 10.5 },
    { text: "ach", absoluteBeat: 11 },
    { text: "now", absoluteBeat: 11.5 },
    { text: "We", absoluteBeat: 12 },
    { text: "want", absoluteBeat: 13 },
    { text: "Mo", absoluteBeat: 14 },
    { text: "shi", absoluteBeat: 14.5 },
    { text: "ach", absoluteBeat: 15 },
    { text: "now", absoluteBeat: 15.5 },
    { text: "We", absoluteBeat: 16 },
    { text: "don't", absoluteBeat: 17 },
    { text: "want", absoluteBeat: 18 },
    { text: "to", absoluteBeat: 18.5 },
    { text: "wait", absoluteBeat: 19 },
  ],
  settings: {
    tempo: 100,
    timeSignature: { numerator: 4, denominator: 4 },
  },
};
