// Ochila Lakel (אוחילה לאל)
// Key: F Major / D minor, Time: 4/4
// UPDATED: All 17 rests from MusicXML
import { SongData } from "./types";

export const ochilaLakelUpdated: SongData = {
  id: "default-ochila-lakel-updated",
  name: "Ochila Lakel (Updated)",
  hebrewName: "אוחילה לאל",
  description: "גלעד פוטולסקי - תזמורת שלהבת",
  notes: [
    // ═══════════════════════════════════════════════════════════════════
    // SECTION A (Measures 1-12)
    // ═══════════════════════════════════════════════════════════════════
    { id: "ochila-r1", pitch: "REST", duration: 1.5, absoluteBeat: 0 },
    { id: "ochila-1", pitch: "A4", duration: 0.5, absoluteBeat: 1.5 },
    { id: "ochila-2", pitch: "A4", duration: 0.5, absoluteBeat: 2.0 },
    { id: "ochila-3", pitch: "F4", duration: 0.5, absoluteBeat: 2.5 },
    { id: "ochila-4", pitch: "G4", duration: 0.5, absoluteBeat: 3.0 },
    { id: "ochila-5", pitch: "A4", duration: 0.5, absoluteBeat: 3.5 },
    { id: "ochila-6", pitch: "G4", duration: 4.0, absoluteBeat: 4.0 },
    { id: "ochila-r2", pitch: "REST", duration: 2.0, absoluteBeat: 8.0 },
    { id: "ochila-7", pitch: "G4", duration: 0.5, absoluteBeat: 10.0 },
    { id: "ochila-8", pitch: "A4", duration: 0.5, absoluteBeat: 10.5 },
    { id: "ochila-9", pitch: "Bb4", duration: 0.5, absoluteBeat: 11.0 },
    { id: "ochila-10", pitch: "G4", duration: 0.5, absoluteBeat: 11.5 },
    { id: "ochila-11", pitch: "A4", duration: 4.0, absoluteBeat: 12.0 },
    { id: "ochila-12", pitch: "C5", duration: 2.0, absoluteBeat: 16.0 },
    { id: "ochila-13", pitch: "Bb4", duration: 1.0, absoluteBeat: 18.0 },
    { id: "ochila-14", pitch: "A4", duration: 1.0, absoluteBeat: 19.0 },
    { id: "ochila-15", pitch: "Bb4", duration: 1.5, absoluteBeat: 20.0 },
    { id: "ochila-16", pitch: "A4", duration: 0.5, absoluteBeat: 21.5 },
    { id: "ochila-17", pitch: "G4", duration: 2.0, absoluteBeat: 22.0 },
    { id: "ochila-r3", pitch: "REST", duration: 1.5, absoluteBeat: 24.0 },
    { id: "ochila-18", pitch: "D4", duration: 0.5, absoluteBeat: 25.5 },
    { id: "ochila-19", pitch: "G4", duration: 0.5, absoluteBeat: 26.0 },
    { id: "ochila-20", pitch: "A4", duration: 0.5, absoluteBeat: 26.5 },
    { id: "ochila-21", pitch: "Bb4", duration: 0.5, absoluteBeat: 27.0 },
    { id: "ochila-22", pitch: "G4", duration: 0.5, absoluteBeat: 27.5 },
    { id: "ochila-23", pitch: "F4", duration: 1.5, absoluteBeat: 28.0 },
    { id: "ochila-24", pitch: "E4", duration: 0.5, absoluteBeat: 29.5 },
    { id: "ochila-25", pitch: "D4", duration: 2.0, absoluteBeat: 30.0 },
    { id: "ochila-r4", pitch: "REST", duration: 1.5, absoluteBeat: 32.0 },

    // ═══════════════════════════════════════════════════════════════════
    // SECTION B (Measures 13-24)
    // ═══════════════════════════════════════════════════════════════════
    { id: "ochila-26", pitch: "F4", duration: 0.5, absoluteBeat: 33.5 },
    { id: "ochila-27", pitch: "F4", duration: 0.5, absoluteBeat: 34.0 },
    { id: "ochila-28", pitch: "D4", duration: 0.5, absoluteBeat: 34.5 },
    { id: "ochila-29", pitch: "E4", duration: 0.5, absoluteBeat: 35.0 },
    { id: "ochila-30", pitch: "F4", duration: 0.5, absoluteBeat: 35.5 },
    { id: "ochila-31", pitch: "E4", duration: 4.0, absoluteBeat: 36.0 },
    { id: "ochila-r5", pitch: "REST", duration: 1.5, absoluteBeat: 40.0 },
    { id: "ochila-32", pitch: "E4", duration: 0.5, absoluteBeat: 41.5 },
    { id: "ochila-33", pitch: "G4", duration: 1.0, absoluteBeat: 42.0 },
    { id: "ochila-34", pitch: "E4", duration: 1.0, absoluteBeat: 43.0 },
    { id: "ochila-35", pitch: "F4", duration: 1.0, absoluteBeat: 44.0 },
    { id: "ochila-36", pitch: "E4", duration: 0.5, absoluteBeat: 45.0 },
    { id: "ochila-37", pitch: "D4", duration: 2.5, absoluteBeat: 45.5 },
    { id: "ochila-38", pitch: "D4", duration: 1.0, absoluteBeat: 48.0 },
    { id: "ochila-r6", pitch: "REST", duration: 1.0, absoluteBeat: 49.0 },
    { id: "ochila-r7", pitch: "REST", duration: 2.0, absoluteBeat: 50.0 },
    { id: "ochila-r8", pitch: "REST", duration: 1.5, absoluteBeat: 52.0 },
    { id: "ochila-39", pitch: "A3", duration: 0.5, absoluteBeat: 53.5 },
    { id: "ochila-40", pitch: "F4", duration: 0.5, absoluteBeat: 54.0 },
    { id: "ochila-41", pitch: "E4", duration: 0.5, absoluteBeat: 54.5 },
    { id: "ochila-42", pitch: "D4", duration: 0.5, absoluteBeat: 55.0 },
    { id: "ochila-43", pitch: "C#4", duration: 0.5, absoluteBeat: 55.5 },
    { id: "ochila-44", pitch: "D4", duration: 4.0, absoluteBeat: 56.0 },
    { id: "ochila-r9", pitch: "REST", duration: 1.0, absoluteBeat: 60.0 },
    { id: "ochila-45", pitch: "D4", duration: 0.5, absoluteBeat: 61.0 },
    { id: "ochila-46", pitch: "G4", duration: 0.5, absoluteBeat: 61.5 },
    { id: "ochila-47", pitch: "G4", duration: 0.5, absoluteBeat: 62.0 },
    { id: "ochila-48", pitch: "F4", duration: 0.5, absoluteBeat: 62.5 },
    { id: "ochila-49", pitch: "E4", duration: 0.5, absoluteBeat: 63.0 },
    { id: "ochila-50", pitch: "F4", duration: 0.5, absoluteBeat: 63.5 },
    { id: "ochila-51", pitch: "E4", duration: 4.0, absoluteBeat: 64.0 },
    { id: "ochila-52", pitch: "E4", duration: 4.0, absoluteBeat: 68.0 },
    { id: "ochila-53", pitch: "A3", duration: 1.5, absoluteBeat: 72.0 },
    { id: "ochila-54", pitch: "A3", duration: 0.5, absoluteBeat: 73.5 },
    { id: "ochila-55", pitch: "C#4", duration: 1.5, absoluteBeat: 74.0 },
    { id: "ochila-56", pitch: "C#4", duration: 0.5, absoluteBeat: 75.5 },
    { id: "ochila-57", pitch: "E4", duration: 2.0, absoluteBeat: 76.0 },
    { id: "ochila-58", pitch: "G4", duration: 2.0, absoluteBeat: 78.0 },
    { id: "ochila-r10", pitch: "REST", duration: 1.0, absoluteBeat: 80.0 },
    { id: "ochila-59", pitch: "F4", duration: 0.5, absoluteBeat: 81.0 },
    { id: "ochila-60", pitch: "E4", duration: 0.5, absoluteBeat: 81.5 },
    { id: "ochila-61", pitch: "D4", duration: 1.0, absoluteBeat: 82.0 },
    { id: "ochila-62", pitch: "G4", duration: 1.0, absoluteBeat: 83.0 },
    { id: "ochila-63", pitch: "F4", duration: 4.0, absoluteBeat: 84.0 },
    { id: "ochila-r11", pitch: "REST", duration: 1.0, absoluteBeat: 88.0 },
    { id: "ochila-64", pitch: "F4", duration: 0.5, absoluteBeat: 89.0 },
    { id: "ochila-65", pitch: "E4", duration: 0.5, absoluteBeat: 89.5 },
    { id: "ochila-66", pitch: "D4", duration: 1.0, absoluteBeat: 90.0 },
    { id: "ochila-67", pitch: "C#4", duration: 1.0, absoluteBeat: 91.0 },
    { id: "ochila-68", pitch: "D4", duration: 4.0, absoluteBeat: 92.0 },
    { id: "ochila-r12", pitch: "REST", duration: 1.5, absoluteBeat: 96.0 },
    { id: "ochila-69", pitch: "A3", duration: 0.5, absoluteBeat: 97.5 },
    { id: "ochila-70", pitch: "F4", duration: 0.5, absoluteBeat: 98.0 },
    { id: "ochila-71", pitch: "E4", duration: 0.5, absoluteBeat: 98.5 },
    { id: "ochila-72", pitch: "D4", duration: 0.5, absoluteBeat: 99.0 },
    { id: "ochila-73", pitch: "C4", duration: 0.5, absoluteBeat: 99.5 },
    { id: "ochila-74", pitch: "D4", duration: 4.0, absoluteBeat: 100.0 },
    { id: "ochila-r13", pitch: "REST", duration: 1.5, absoluteBeat: 104.0 },
    { id: "ochila-75", pitch: "A4", duration: 0.5, absoluteBeat: 105.5 },
    { id: "ochila-76", pitch: "A4", duration: 0.5, absoluteBeat: 106.0 },
    { id: "ochila-77", pitch: "G4", duration: 0.5, absoluteBeat: 106.5 },
    { id: "ochila-78", pitch: "F4", duration: 0.5, absoluteBeat: 107.0 },
    { id: "ochila-79", pitch: "G4", duration: 0.5, absoluteBeat: 107.5 },
    { id: "ochila-80", pitch: "F4", duration: 4.0, absoluteBeat: 108.0 },
    { id: "ochila-r14", pitch: "REST", duration: 1.5, absoluteBeat: 112.0 },
    { id: "ochila-81", pitch: "F4", duration: 0.5, absoluteBeat: 113.5 },
    { id: "ochila-82", pitch: "F4", duration: 0.5, absoluteBeat: 114.0 },
    { id: "ochila-83", pitch: "E4", duration: 0.5, absoluteBeat: 114.5 },
    { id: "ochila-84", pitch: "D4", duration: 0.5, absoluteBeat: 115.0 },
    { id: "ochila-85", pitch: "C4", duration: 0.5, absoluteBeat: 115.5 },
    { id: "ochila-86", pitch: "D4", duration: 2.0, absoluteBeat: 116.0 },
    { id: "ochila-87", pitch: "G4", duration: 2.0, absoluteBeat: 118.0 },
    { id: "ochila-r15", pitch: "REST", duration: 1.5, absoluteBeat: 120.0 },
    { id: "ochila-88", pitch: "D4", duration: 0.5, absoluteBeat: 121.5 },
    { id: "ochila-89", pitch: "F4", duration: 0.5, absoluteBeat: 122.0 },
    { id: "ochila-90", pitch: "E4", duration: 0.5, absoluteBeat: 122.5 },
    { id: "ochila-91", pitch: "D4", duration: 0.5, absoluteBeat: 123.0 },
    { id: "ochila-92", pitch: "C4", duration: 0.5, absoluteBeat: 123.5 },
    { id: "ochila-93", pitch: "D4", duration: 4.0, absoluteBeat: 124.0 },
    { id: "ochila-r16", pitch: "REST", duration: 1.5, absoluteBeat: 128.0 },
    { id: "ochila-94", pitch: "A4", duration: 0.5, absoluteBeat: 129.5 },
    { id: "ochila-95", pitch: "A4", duration: 0.5, absoluteBeat: 130.0 },
    { id: "ochila-96", pitch: "F4", duration: 0.5, absoluteBeat: 130.5 },
    { id: "ochila-97", pitch: "G4", duration: 0.5, absoluteBeat: 131.0 },
    { id: "ochila-98", pitch: "A4", duration: 0.5, absoluteBeat: 131.5 },
    { id: "ochila-99", pitch: "G4", duration: 4.0, absoluteBeat: 132.0 },
    { id: "ochila-r17", pitch: "REST", duration: 2.0, absoluteBeat: 136.0 },
    { id: "ochila-100", pitch: "G4", duration: 0.5, absoluteBeat: 138.0 },
    { id: "ochila-101", pitch: "A4", duration: 0.5, absoluteBeat: 138.5 },
    { id: "ochila-102", pitch: "Bb4", duration: 0.5, absoluteBeat: 139.0 },
    { id: "ochila-103", pitch: "G4", duration: 0.5, absoluteBeat: 139.5 },
    { id: "ochila-104", pitch: "F4", duration: 1.5, absoluteBeat: 140.0 },
    { id: "ochila-105", pitch: "E4", duration: 0.5, absoluteBeat: 141.5 },
    { id: "ochila-106", pitch: "D4", duration: 2.0, absoluteBeat: 142.0 },
  ],

  repeatMarkers: [],

  lyrics: [],

  settings: {
    tempo: 160,
    timeSignature: { numerator: 4, denominator: 4 },
    staffLines: 5,
  },

  releaseDate: "2026-02-03",

  transcriptionNotes: {
    original: {
      key: "F Major / D minor",
      timeSignature: "4/4",
      features: [
        "17 rests added from MusicXML source",
        "Traditional Jewish liturgical song",
        "Accidentals: Bb4, C#4",
      ],
    },
    changes: [
      {
        what: "Added 17 rests from MusicXML extraction",
        why: "Original sheet music has rests that were missing from first transcription",
      },
    ],
    sources: {
      sheetMusic: "Israeli Note - Ochila Lakel (Gilad Potolsky)",
    },
    transcribedDate: "2026-02-04",
  },
};
