// Shevet Achim Ve'Achayot (שבת אחים ואחיות)
// Key: C Major / A minor, Time: 4/4
// UPDATED: All 27 rests + timing corrections from editor
import { SongData } from "./types";

export const shevetAchimUpdated: SongData = {
  id: "default-shevet-achim-updated",
  name: "Shevet Achim (Updated)",
  hebrewName: "שבת אחים ואחיות",
  description: "עידן רייכל - הנה מה טוב ומה נעים",
  notes: [
    // ═══════════════════════════════════════════════════════════════════
    // SECTION A - Opening (with pickup rest)
    // ═══════════════════════════════════════════════════════════════════
    { id: "shevet-r1", pitch: "REST", duration: 0.5, absoluteBeat: 0 },
    { id: "shevet-1", pitch: "C5", duration: 0.5, absoluteBeat: 0.5 },
    { id: "shevet-2", pitch: "C5", duration: 0.5, absoluteBeat: 1 },
    { id: "shevet-3", pitch: "C5", duration: 0.5, absoluteBeat: 1.5 },
    { id: "shevet-4", pitch: "B4", duration: 1, absoluteBeat: 2 },
    { id: "shevet-5", pitch: "A4", duration: 1, absoluteBeat: 3 },
    { id: "shevet-6", pitch: "G4", duration: 1, absoluteBeat: 4 },
    { id: "shevet-7", pitch: "A4", duration: 1, absoluteBeat: 5 },
    { id: "shevet-8", pitch: "A4", duration: 1, absoluteBeat: 6 },
    { id: "shevet-r2", pitch: "REST", duration: 1, absoluteBeat: 7 },
    { id: "shevet-r3", pitch: "REST", duration: 0.5, absoluteBeat: 8 },
    { id: "shevet-9", pitch: "C5", duration: 0.5, absoluteBeat: 8.5 },
    { id: "shevet-10", pitch: "C5", duration: 0.5, absoluteBeat: 9 },
    { id: "shevet-11", pitch: "C5", duration: 0.5, absoluteBeat: 9.5 },
    { id: "shevet-12", pitch: "B4", duration: 1, absoluteBeat: 10 },
    { id: "shevet-13", pitch: "A4", duration: 1, absoluteBeat: 11 },
    { id: "shevet-14", pitch: "G4", duration: 1, absoluteBeat: 12 },
    { id: "shevet-15", pitch: "A4", duration: 1, absoluteBeat: 13 },
    { id: "shevet-16", pitch: "A4", duration: 1, absoluteBeat: 14 },
    { id: "shevet-r4", pitch: "REST", duration: 1, absoluteBeat: 15 },
    { id: "shevet-r5", pitch: "REST", duration: 0.5, absoluteBeat: 16 },
    { id: "shevet-17", pitch: "G4", duration: 0.5, absoluteBeat: 16.5 },
    { id: "shevet-18", pitch: "G4", duration: 0.5, absoluteBeat: 17 },
    { id: "shevet-19", pitch: "G4", duration: 0.5, absoluteBeat: 17.5 },
    { id: "shevet-20", pitch: "C5", duration: 0.5, absoluteBeat: 18 },
    { id: "shevet-21", pitch: "C5", duration: 0.5, absoluteBeat: 18.5 },
    { id: "shevet-22", pitch: "C5", duration: 0.5, absoluteBeat: 19 },
    { id: "shevet-23", pitch: "E5", duration: 0.5, absoluteBeat: 19.5 },
    { id: "shevet-24", pitch: "D5", duration: 0.75, absoluteBeat: 20 },
    { id: "shevet-25", pitch: "C5", duration: 0.25, absoluteBeat: 20.5 },
    { id: "shevet-26", pitch: "A4", duration: 1, absoluteBeat: 21 },
    { id: "shevet-r6", pitch: "REST", duration: 2, absoluteBeat: 22 },

    // ═══════════════════════════════════════════════════════════════════
    // SECTION B - Bridge
    // ═══════════════════════════════════════════════════════════════════
    { id: "shevet-r7", pitch: "REST", duration: 0.5, absoluteBeat: 24 },
    { id: "shevet-27", pitch: "D5", duration: 0.5, absoluteBeat: 24.5 },
    { id: "shevet-28", pitch: "D5", duration: 0.5, absoluteBeat: 25 },
    { id: "shevet-29", pitch: "C5", duration: 0.5, absoluteBeat: 25.5 },
    { id: "shevet-30", pitch: "D5", duration: 0.5, absoluteBeat: 26 },
    { id: "shevet-31", pitch: "C5", duration: 0.5, absoluteBeat: 26.5 },
    { id: "shevet-32", pitch: "D5", duration: 0.5, absoluteBeat: 27 },
    { id: "shevet-33", pitch: "E5", duration: 0.5, absoluteBeat: 27.5 },
    { id: "shevet-34", pitch: "A4", duration: 1, absoluteBeat: 28 },
    { id: "shevet-r8", pitch: "REST", duration: 0.5, absoluteBeat: 29 },
    { id: "shevet-35", pitch: "C5", duration: 0.5, absoluteBeat: 29.5 },
    { id: "shevet-36", pitch: "B4", duration: 0.5, absoluteBeat: 30 },
    { id: "shevet-37", pitch: "A4", duration: 0.5, absoluteBeat: 30.5 },
    { id: "shevet-r9", pitch: "REST", duration: 1, absoluteBeat: 31 },
    { id: "shevet-38", pitch: "A4", duration: 1, absoluteBeat: 32 },
    { id: "shevet-r10", pitch: "REST", duration: 1, absoluteBeat: 33 },
    { id: "shevet-r11", pitch: "REST", duration: 2, absoluteBeat: 34 },
    { id: "shevet-r12", pitch: "REST", duration: 0.5, absoluteBeat: 36 },
    { id: "shevet-r13", pitch: "REST", duration: 0.75, absoluteBeat: 36.5 },
    { id: "shevet-39", pitch: "D5", duration: 0.25, absoluteBeat: 37 },
    { id: "shevet-40", pitch: "D5", duration: 0.5, absoluteBeat: 37.5 },
    { id: "shevet-41", pitch: "C5", duration: 0.5, absoluteBeat: 38 },
    { id: "shevet-42", pitch: "D5", duration: 0.75, absoluteBeat: 38.5 },
    { id: "shevet-43", pitch: "C5", duration: 0.25, absoluteBeat: 39 },
    { id: "shevet-44", pitch: "D5", duration: 0.5, absoluteBeat: 39.5 },
    { id: "shevet-45", pitch: "E5", duration: 0.5, absoluteBeat: 40 },
    { id: "shevet-r14", pitch: "REST", duration: 0.5, absoluteBeat: 40.5 },
    { id: "shevet-46", pitch: "A4", duration: 2, absoluteBeat: 41 },
    { id: "shevet-r15", pitch: "REST", duration: 2, absoluteBeat: 43 },
    { id: "shevet-r16", pitch: "REST", duration: 0.5, absoluteBeat: 45 },
    { id: "shevet-r17", pitch: "REST", duration: 0.5, absoluteBeat: 45.5 },
    { id: "shevet-47", pitch: "G4", duration: 0.5, absoluteBeat: 46 },
    { id: "shevet-48", pitch: "G4", duration: 0.5, absoluteBeat: 46.5 },
    { id: "shevet-49", pitch: "G4", duration: 0.5, absoluteBeat: 47 },
    { id: "shevet-50", pitch: "C5", duration: 0.5, absoluteBeat: 47.5 },
    { id: "shevet-51", pitch: "C5", duration: 0.5, absoluteBeat: 48 },
    { id: "shevet-52", pitch: "C5", duration: 0.5, absoluteBeat: 48.5 },
    { id: "shevet-53", pitch: "E5", duration: 0.5, absoluteBeat: 49 },
    { id: "shevet-r18", pitch: "REST", duration: 0.5, absoluteBeat: 49.5 },
    { id: "shevet-54", pitch: "D5", duration: 0.75, absoluteBeat: 50 },
    { id: "shevet-55", pitch: "C5", duration: 0.25, absoluteBeat: 50.5 },
    { id: "shevet-56", pitch: "A4", duration: 1, absoluteBeat: 51 },
    { id: "shevet-r19", pitch: "REST", duration: 1.5, absoluteBeat: 52 },
    { id: "shevet-57", pitch: "D5", duration: 0.5, absoluteBeat: 53.5 },
    { id: "shevet-r20", pitch: "REST", duration: 0.5, absoluteBeat: 54 },
    { id: "shevet-58", pitch: "D5", duration: 0.5, absoluteBeat: 54.5 },
    { id: "shevet-59", pitch: "C5", duration: 0.5, absoluteBeat: 55 },
    { id: "shevet-60", pitch: "D5", duration: 0.5, absoluteBeat: 55.5 },
    { id: "shevet-61", pitch: "C5", duration: 0.5, absoluteBeat: 56 },
    { id: "shevet-62", pitch: "D5", duration: 0.5, absoluteBeat: 56.5 },
    { id: "shevet-63", pitch: "C5", duration: 0.5, absoluteBeat: 57 },
    { id: "shevet-64", pitch: "D5", duration: 0.5, absoluteBeat: 57.5 },
    { id: "shevet-65", pitch: "E5", duration: 0.5, absoluteBeat: 58 },
    { id: "shevet-66", pitch: "E5", duration: 0.75, absoluteBeat: 58.5 },
    { id: "shevet-67", pitch: "D5", duration: 0.25, absoluteBeat: 59 },
    { id: "shevet-68", pitch: "C5", duration: 0.75, absoluteBeat: 59.5 },
    { id: "shevet-69", pitch: "B4", duration: 0.25, absoluteBeat: 60 },
    { id: "shevet-70", pitch: "A4", duration: 2, absoluteBeat: 60.5 },
    { id: "shevet-r21", pitch: "REST", duration: 0.5, absoluteBeat: 62.5 },
    { id: "shevet-71", pitch: "A4", duration: 0.5, absoluteBeat: 63 },
    { id: "shevet-72", pitch: "A4", duration: 0.5, absoluteBeat: 63.5 },
    { id: "shevet-73", pitch: "A4", duration: 0.5, absoluteBeat: 64 },
    { id: "shevet-74", pitch: "C5", duration: 0.5, absoluteBeat: 64.5 },
    { id: "shevet-75", pitch: "A4", duration: 0.5, absoluteBeat: 65 },
    { id: "shevet-76", pitch: "C5", duration: 0.5, absoluteBeat: 65.5 },
    { id: "shevet-77", pitch: "E5", duration: 0.5, absoluteBeat: 66 },
    { id: "shevet-78", pitch: "D5", duration: 2, absoluteBeat: 66.5 },
    { id: "shevet-79", pitch: "C5", duration: 1, absoluteBeat: 68.5 },
    { id: "shevet-80", pitch: "D5", duration: 1, absoluteBeat: 69.5 },
    { id: "shevet-81", pitch: "C5", duration: 0.75, absoluteBeat: 70.5 },
    { id: "shevet-82", pitch: "B4", duration: 0.25, absoluteBeat: 71 },
    { id: "shevet-83", pitch: "A4", duration: 1, absoluteBeat: 71.5 },
    { id: "shevet-84", pitch: "A4", duration: 1, absoluteBeat: 72.5 },
    { id: "shevet-85", pitch: "B4", duration: 1, absoluteBeat: 73.5 },
    { id: "shevet-86", pitch: "C5", duration: 1, absoluteBeat: 74.5 },
    { id: "shevet-r22", pitch: "REST", duration: 1, absoluteBeat: 75.5 },
    { id: "shevet-87", pitch: "C5", duration: 1, absoluteBeat: 76.5 },
    { id: "shevet-88", pitch: "E5", duration: 1, absoluteBeat: 77.5 },
    { id: "shevet-89", pitch: "D5", duration: 1, absoluteBeat: 78.5 },
    { id: "shevet-90", pitch: "A4", duration: 1, absoluteBeat: 79.5 },
    { id: "shevet-91", pitch: "D5", duration: 1, absoluteBeat: 80.5 },
    { id: "shevet-92", pitch: "E5", duration: 1, absoluteBeat: 81.5 },
    { id: "shevet-93", pitch: "C5", duration: 1, absoluteBeat: 82.5 },
    { id: "shevet-r23", pitch: "REST", duration: 1, absoluteBeat: 83.5 },
    { id: "shevet-94", pitch: "C5", duration: 1, absoluteBeat: 84.5 },
    { id: "shevet-95", pitch: "A4", duration: 1, absoluteBeat: 85.5 },
    { id: "shevet-96", pitch: "G4", duration: 1, absoluteBeat: 86.5 },
    { id: "shevet-97", pitch: "G4", duration: 1, absoluteBeat: 87.5 },
    { id: "shevet-98", pitch: "C5", duration: 1, absoluteBeat: 88.5 },
    { id: "shevet-99", pitch: "E5", duration: 1, absoluteBeat: 89.5 },
    { id: "shevet-100", pitch: "D5", duration: 1, absoluteBeat: 90.5 },
    { id: "shevet-r24", pitch: "REST", duration: 1, absoluteBeat: 91.5 },
    { id: "shevet-101", pitch: "D5", duration: 1, absoluteBeat: 92.5 },
    { id: "shevet-102", pitch: "E5", duration: 1, absoluteBeat: 93.5 },
    { id: "shevet-103", pitch: "C5", duration: 1, absoluteBeat: 94.5 },
    { id: "shevet-104", pitch: "A4", duration: 1, absoluteBeat: 95.5 },
    { id: "shevet-105", pitch: "A4", duration: 1, absoluteBeat: 96.5 },
    { id: "shevet-106", pitch: "G4", duration: 1, absoluteBeat: 97.5 },
    { id: "shevet-107", pitch: "A4", duration: 1, absoluteBeat: 98.5 },
    { id: "shevet-108", pitch: "G4", duration: 1, absoluteBeat: 99.5 },
    { id: "shevet-109", pitch: "A4", duration: 1, absoluteBeat: 100.5 },
    { id: "shevet-110", pitch: "B4", duration: 1, absoluteBeat: 101.5 },
    { id: "shevet-111", pitch: "C5", duration: 2, absoluteBeat: 102.5 },
    { id: "shevet-r25", pitch: "REST", duration: 2, absoluteBeat: 104.5 },
    { id: "shevet-112", pitch: "D5", duration: 0.5, absoluteBeat: 106.5 },
    { id: "shevet-113", pitch: "D5", duration: 0.5, absoluteBeat: 107 },
    { id: "shevet-114", pitch: "C5", duration: 0.5, absoluteBeat: 107.5 },
    { id: "shevet-115", pitch: "D5", duration: 1, absoluteBeat: 108 },
    { id: "shevet-116", pitch: "C5", duration: 0.5, absoluteBeat: 109 },
    { id: "shevet-117", pitch: "D5", duration: 0.5, absoluteBeat: 109.5 },
    { id: "shevet-118", pitch: "E5", duration: 0.5, absoluteBeat: 110 },
    { id: "shevet-119", pitch: "C5", duration: 0.75, absoluteBeat: 110.5 },
    { id: "shevet-120", pitch: "B4", duration: 0.25, absoluteBeat: 111.25 },
    { id: "shevet-121", pitch: "A4", duration: 1, absoluteBeat: 111.5 },
    { id: "shevet-r26", pitch: "REST", duration: 2, absoluteBeat: 112.5 },
    { id: "shevet-r27", pitch: "REST", duration: 4, absoluteBeat: 114.5 },
  ],

  repeatMarkers: [],

  lyrics: [],

  settings: {
    tempo: 100,
    timeSignature: { numerator: 4, denominator: 4 },
    staffLines: 5,
  },

  releaseDate: "2026-02-03",

  transcriptionNotes: {
    original: {
      key: "C Major / A minor",
      timeSignature: "4/4",
      features: [
        "27 rests from MusicXML source",
        "Timing corrections from editor",
        "Dotted rhythms throughout",
        "No accidentals - pure A minor",
      ],
    },
    changes: [
      {
        what: "Timing corrections for dotted note sequences",
        why: "Adjusted absoluteBeat values for better playback feel",
      },
    ],
    sources: {
      sheetMusic: "Israeli Note - Shevet Achim Ve'Achayot (Idan Raichel)",
    },
    transcribedDate: "2026-02-04",
  },
};
