// Yesh Bi Od Koach (יש בי עוד כח)
// Key: Db Major / Bb minor, Time: 2/2
// UPDATED: All 10 rests from MusicXML
import { SongData } from "./types";

export const yeshBiOdKoachUpdated: SongData = {
  id: "default-yesh-bi-od-koach-updated",
  name: "Yesh Bi Od Koach (Updated)",
  hebrewName: "יש בי עוד כח",
  description: "עידן רייכל",
  notes: [
    // ═══════════════════════════════════════════════════════════════════
    // VERSE 1 (Measures 1-8)
    // ═══════════════════════════════════════════════════════════════════
    { id: "yesh-1", pitch: "F4", duration: 1.5, absoluteBeat: 0 },
    { id: "yesh-2", pitch: "Db4", duration: 0.5, absoluteBeat: 1.5 },
    { id: "yesh-3", pitch: "Db4", duration: 0.5, absoluteBeat: 2.0 },
    { id: "yesh-4", pitch: "F4", duration: 1.0, absoluteBeat: 2.5 },
    { id: "yesh-5", pitch: "Gb4", duration: 0.5, absoluteBeat: 3.5 },
    { id: "yesh-6", pitch: "Gb4", duration: 1.5, absoluteBeat: 4.0 },
    { id: "yesh-7", pitch: "F4", duration: 0.5, absoluteBeat: 5.5 },
    { id: "yesh-8", pitch: "F4", duration: 0.5, absoluteBeat: 6.0 },
    { id: "yesh-9", pitch: "Eb4", duration: 1.0, absoluteBeat: 6.5 },
    { id: "yesh-10", pitch: "F4", duration: 0.5, absoluteBeat: 7.5 },
    { id: "yesh-11", pitch: "F4", duration: 1.5, absoluteBeat: 8.0 },
    { id: "yesh-12", pitch: "Db4", duration: 0.5, absoluteBeat: 9.5 },
    { id: "yesh-13", pitch: "Db4", duration: 0.5, absoluteBeat: 10.0 },
    { id: "yesh-14", pitch: "F4", duration: 1.0, absoluteBeat: 10.5 },
    { id: "yesh-15", pitch: "Gb4", duration: 0.5, absoluteBeat: 11.5 },
    { id: "yesh-16", pitch: "Gb4", duration: 1.5, absoluteBeat: 12.0 },
    { id: "yesh-17", pitch: "F4", duration: 0.5, absoluteBeat: 13.5 },
    { id: "yesh-18", pitch: "F4", duration: 1.0, absoluteBeat: 14.0 },
    { id: "yesh-r1", pitch: "REST", duration: 0.5, absoluteBeat: 15.0 },
    { id: "yesh-19", pitch: "Eb4", duration: 0.5, absoluteBeat: 15.5 },
    { id: "yesh-20", pitch: "Gb4", duration: 1.5, absoluteBeat: 16.0 },
    { id: "yesh-21", pitch: "Eb4", duration: 0.5, absoluteBeat: 17.5 },
    { id: "yesh-22", pitch: "Eb4", duration: 0.5, absoluteBeat: 18.0 },
    { id: "yesh-23", pitch: "Gb4", duration: 1.0, absoluteBeat: 18.5 },
    { id: "yesh-24", pitch: "Ab4", duration: 0.5, absoluteBeat: 19.5 },
    { id: "yesh-25", pitch: "Ab4", duration: 1.5, absoluteBeat: 20.0 },
    { id: "yesh-26", pitch: "Gb4", duration: 0.5, absoluteBeat: 21.5 },
    { id: "yesh-27", pitch: "Gb4", duration: 1.0, absoluteBeat: 22.0 },
    { id: "yesh-r2", pitch: "REST", duration: 0.5, absoluteBeat: 23.0 },
    { id: "yesh-28", pitch: "F4", duration: 0.5, absoluteBeat: 23.5 },
    { id: "yesh-29", pitch: "Gb4", duration: 1.5, absoluteBeat: 24.0 },
    { id: "yesh-30", pitch: "Eb4", duration: 0.5, absoluteBeat: 25.5 },
    { id: "yesh-31", pitch: "Eb4", duration: 0.5, absoluteBeat: 26.0 },
    { id: "yesh-32", pitch: "F4", duration: 1.0, absoluteBeat: 26.5 },
    { id: "yesh-33", pitch: "Gb4", duration: 0.5, absoluteBeat: 27.5 },
    { id: "yesh-34", pitch: "Gb4", duration: 1.5, absoluteBeat: 28.0 },
    { id: "yesh-35", pitch: "F4", duration: 0.5, absoluteBeat: 29.5 },
    { id: "yesh-36", pitch: "F4", duration: 0.5, absoluteBeat: 30.0 },
    { id: "yesh-37", pitch: "Eb4", duration: 1.0, absoluteBeat: 30.5 },
    { id: "yesh-38", pitch: "F4", duration: 0.5, absoluteBeat: 31.5 },

    // ═══════════════════════════════════════════════════════════════════
    // VERSE 2 (Measures 9-16)
    // ═══════════════════════════════════════════════════════════════════
    { id: "yesh-39", pitch: "F4", duration: 2.0, absoluteBeat: 32.0 },
    { id: "yesh-40", pitch: "Db4", duration: 0.5, absoluteBeat: 34.0 },
    { id: "yesh-41", pitch: "F4", duration: 1.0, absoluteBeat: 34.5 },
    { id: "yesh-42", pitch: "Gb4", duration: 0.5, absoluteBeat: 35.5 },
    { id: "yesh-43", pitch: "Gb4", duration: 1.5, absoluteBeat: 36.0 },
    { id: "yesh-44", pitch: "F4", duration: 1.0, absoluteBeat: 37.5 },
    { id: "yesh-45", pitch: "Eb4", duration: 1.0, absoluteBeat: 38.5 },
    { id: "yesh-46", pitch: "F4", duration: 0.5, absoluteBeat: 39.5 },
    { id: "yesh-47", pitch: "F4", duration: 1.5, absoluteBeat: 40.0 },
    { id: "yesh-48", pitch: "Db4", duration: 1.0, absoluteBeat: 41.5 },
    { id: "yesh-49", pitch: "F4", duration: 1.0, absoluteBeat: 42.5 },
    { id: "yesh-50", pitch: "Gb4", duration: 0.5, absoluteBeat: 43.5 },
    { id: "yesh-51", pitch: "Gb4", duration: 1.5, absoluteBeat: 44.0 },
    { id: "yesh-52", pitch: "F4", duration: 1.5, absoluteBeat: 45.5 },
    { id: "yesh-r3", pitch: "REST", duration: 0.5, absoluteBeat: 47.0 },
    { id: "yesh-53", pitch: "Eb4", duration: 0.5, absoluteBeat: 47.5 },
    { id: "yesh-54", pitch: "Gb4", duration: 1.5, absoluteBeat: 48.0 },
    { id: "yesh-55", pitch: "Eb4", duration: 0.5, absoluteBeat: 49.5 },
    { id: "yesh-56", pitch: "Eb4", duration: 0.5, absoluteBeat: 50.0 },
    { id: "yesh-57", pitch: "Gb4", duration: 1.0, absoluteBeat: 50.5 },
    { id: "yesh-58", pitch: "Ab4", duration: 0.5, absoluteBeat: 51.5 },
    { id: "yesh-59", pitch: "Ab4", duration: 1.5, absoluteBeat: 52.0 },
    { id: "yesh-60", pitch: "Gb4", duration: 0.5, absoluteBeat: 53.5 },
    { id: "yesh-61", pitch: "Gb4", duration: 0.5, absoluteBeat: 54.0 },
    { id: "yesh-62", pitch: "F4", duration: 1.0, absoluteBeat: 54.5 },
    { id: "yesh-63", pitch: "Gb4", duration: 0.5, absoluteBeat: 55.5 },
    { id: "yesh-64", pitch: "Gb4", duration: 2.0, absoluteBeat: 56.0 },
    { id: "yesh-65", pitch: "Eb4", duration: 0.5, absoluteBeat: 58.0 },
    { id: "yesh-66", pitch: "F4", duration: 1.0, absoluteBeat: 58.5 },
    { id: "yesh-67", pitch: "Gb4", duration: 0.5, absoluteBeat: 59.5 },
    { id: "yesh-68", pitch: "Gb4", duration: 1.5, absoluteBeat: 60.0 },
    { id: "yesh-69", pitch: "F4", duration: 0.5, absoluteBeat: 61.5 },
    { id: "yesh-70", pitch: "F4", duration: 0.5, absoluteBeat: 62.0 },
    { id: "yesh-71", pitch: "Eb4", duration: 1.0, absoluteBeat: 62.5 },
    { id: "yesh-72", pitch: "Db4", duration: 0.5, absoluteBeat: 63.5 },

    // ═══════════════════════════════════════════════════════════════════
    // BRIDGE (Measures 17-24)
    // ═══════════════════════════════════════════════════════════════════
    { id: "yesh-73", pitch: "Db4", duration: 1.5, absoluteBeat: 64.0 },
    { id: "yesh-74", pitch: "Db4", duration: 1.0, absoluteBeat: 65.5 },
    { id: "yesh-75", pitch: "Bb4", duration: 1.0, absoluteBeat: 66.5 },
    { id: "yesh-76", pitch: "Ab4", duration: 0.5, absoluteBeat: 67.5 },
    { id: "yesh-77", pitch: "Ab4", duration: 1.5, absoluteBeat: 68.0 },
    { id: "yesh-78", pitch: "Gb4", duration: 0.5, absoluteBeat: 69.5 },
    { id: "yesh-79", pitch: "Gb4", duration: 0.5, absoluteBeat: 70.0 },
    { id: "yesh-80", pitch: "F4", duration: 1.0, absoluteBeat: 70.5 },
    { id: "yesh-81", pitch: "Gb4", duration: 0.5, absoluteBeat: 71.5 },
    { id: "yesh-82", pitch: "Gb4", duration: 1.5, absoluteBeat: 72.0 },
    { id: "yesh-83", pitch: "Bb3", duration: 0.5, absoluteBeat: 73.5 },
    { id: "yesh-84", pitch: "Bb3", duration: 0.5, absoluteBeat: 74.0 },
    { id: "yesh-85", pitch: "Gb4", duration: 1.0, absoluteBeat: 74.5 },
    { id: "yesh-86", pitch: "F4", duration: 0.5, absoluteBeat: 75.5 },
    { id: "yesh-87", pitch: "F4", duration: 1.5, absoluteBeat: 76.0 },
    { id: "yesh-88", pitch: "Eb4", duration: 0.5, absoluteBeat: 77.5 },
    { id: "yesh-89", pitch: "Eb4", duration: 1.0, absoluteBeat: 78.0 },
    { id: "yesh-r4", pitch: "REST", duration: 0.5, absoluteBeat: 79.0 },
    { id: "yesh-90", pitch: "Eb4", duration: 0.5, absoluteBeat: 79.5 },
    { id: "yesh-91", pitch: "Db4", duration: 1.0, absoluteBeat: 80.0 },
    { id: "yesh-r5", pitch: "REST", duration: 1.0, absoluteBeat: 81.0 },
    { id: "yesh-92", pitch: "Bb3", duration: 1.0, absoluteBeat: 82.0 },
    { id: "yesh-93", pitch: "Db4", duration: 1.0, absoluteBeat: 83.0 },

    // ═══════════════════════════════════════════════════════════════════
    // CHORUS (Measures 25-32)
    // ═══════════════════════════════════════════════════════════════════
    { id: "yesh-94", pitch: "F4", duration: 1.5, absoluteBeat: 84.0 },
    { id: "yesh-95", pitch: "Eb4", duration: 1.5, absoluteBeat: 85.5 },
    { id: "yesh-r6", pitch: "REST", duration: 0.5, absoluteBeat: 87.0 },
    { id: "yesh-96", pitch: "Db4", duration: 0.5, absoluteBeat: 87.5 },
    { id: "yesh-97", pitch: "F4", duration: 1.5, absoluteBeat: 88.0 },
    { id: "yesh-98", pitch: "Db4", duration: 1.0, absoluteBeat: 89.5 },
    { id: "yesh-99", pitch: "F4", duration: 1.0, absoluteBeat: 90.5 },
    { id: "yesh-100", pitch: "Gb4", duration: 0.5, absoluteBeat: 91.5 },
    { id: "yesh-101", pitch: "Gb4", duration: 1.5, absoluteBeat: 92.0 },
    { id: "yesh-102", pitch: "F4", duration: 1.0, absoluteBeat: 93.5 },
    { id: "yesh-103", pitch: "Eb4", duration: 1.0, absoluteBeat: 94.5 },
    { id: "yesh-104", pitch: "Db4", duration: 0.5, absoluteBeat: 95.5 },
    { id: "yesh-105", pitch: "Db4", duration: 1.0, absoluteBeat: 96.0 },
    { id: "yesh-r7", pitch: "REST", duration: 1.0, absoluteBeat: 97.0 },
    { id: "yesh-106", pitch: "Db4", duration: 0.5, absoluteBeat: 98.0 },
    { id: "yesh-107", pitch: "Bb4", duration: 1.0, absoluteBeat: 98.5 },
    { id: "yesh-108", pitch: "Ab4", duration: 0.5, absoluteBeat: 99.5 },
    { id: "yesh-109", pitch: "Ab4", duration: 1.5, absoluteBeat: 100.0 },
    { id: "yesh-110", pitch: "Gb4", duration: 0.5, absoluteBeat: 101.5 },
    { id: "yesh-111", pitch: "Gb4", duration: 0.5, absoluteBeat: 102.0 },
    { id: "yesh-112", pitch: "F4", duration: 1.0, absoluteBeat: 102.5 },
    { id: "yesh-113", pitch: "Gb4", duration: 0.5, absoluteBeat: 103.5 },
    { id: "yesh-114", pitch: "Gb4", duration: 1.0, absoluteBeat: 104.0 },
    { id: "yesh-r8", pitch: "REST", duration: 1.0, absoluteBeat: 105.0 },
    { id: "yesh-115", pitch: "Bb3", duration: 1.0, absoluteBeat: 106.0 },
    { id: "yesh-116", pitch: "Gb4", duration: 1.0, absoluteBeat: 107.0 },
    { id: "yesh-117", pitch: "F4", duration: 1.5, absoluteBeat: 108.0 },
    { id: "yesh-118", pitch: "Eb4", duration: 0.5, absoluteBeat: 109.5 },
    { id: "yesh-119", pitch: "Eb4", duration: 0.5, absoluteBeat: 110.0 },
    { id: "yesh-120", pitch: "Eb4", duration: 1.0, absoluteBeat: 110.5 },
    { id: "yesh-121", pitch: "Db4", duration: 0.5, absoluteBeat: 111.5 },
    { id: "yesh-122", pitch: "Db4", duration: 1.0, absoluteBeat: 112.0 },
    { id: "yesh-r9", pitch: "REST", duration: 1.0, absoluteBeat: 113.0 },
    { id: "yesh-123", pitch: "Bb3", duration: 1.0, absoluteBeat: 114.0 },
    { id: "yesh-124", pitch: "Db4", duration: 1.0, absoluteBeat: 115.0 },
    { id: "yesh-125", pitch: "F4", duration: 1.5, absoluteBeat: 116.0 },
    { id: "yesh-126", pitch: "Eb4", duration: 0.5, absoluteBeat: 117.5 },
    { id: "yesh-127", pitch: "Eb4", duration: 0.5, absoluteBeat: 118.0 },
    { id: "yesh-128", pitch: "Db4", duration: 1.0, absoluteBeat: 118.5 },
    { id: "yesh-129", pitch: "Db4", duration: 0.5, absoluteBeat: 119.5 },
    { id: "yesh-130", pitch: "Db4", duration: 4.0, absoluteBeat: 120.0 },
    { id: "yesh-r10", pitch: "REST", duration: 4.0, absoluteBeat: 124.0 },
  ],

  repeatMarkers: [],

  lyrics: [],

  settings: {
    tempo: 72,
    timeSignature: { numerator: 2, denominator: 2 },
    staffLines: 5,
  },

  releaseDate: "2026-02-03",

  transcriptionNotes: {
    original: {
      key: "Db Major / Bb minor",
      timeSignature: "2/2",
      features: [
        "10 rests added from MusicXML source",
        "Original key preserved (Db major with flats)",
        "Distinctive Idan Raichel style",
      ],
    },
    changes: [
      {
        what: "Added 10 rests from MusicXML extraction",
        why: "Original sheet music has rests that were missing from first transcription",
      },
    ],
    sources: {
      sheetMusic: "Israeli Note - Yesh Bi Od Koach (Idan Raichel)",
    },
    transcribedDate: "2026-02-04",
  },
};
